(defun my-color-theme ()
  "Color theme by Geoff Jacobsen, created 2008-04-09."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "white")
      (background-mode . light)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "black")
      (foreground-color . "MidnightBlue")
      (mouse-color . "LawnGreen")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((align-highlight-change-face . highlight)
      (align-highlight-nochange-face . secondary-selection)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (browse-kill-ring-separator-face . bold)
      (compilation-message-face . underline)
      (dvc-annotate-very-old-color . "#3F3FFF")
      (dvc-button-face . bold)
      (dvc-fileinfo-printer-interface . full)
      (dvc-mouse-face . highlight)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (ispell-highlight-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (Buffer-menu-buffer-face ((t (nil))))
     (CUA-global-mark-face ((t (nil))))
     (CUA-rectangle-face ((t (nil))))
     (CUA-rectangle-noselect-face ((t (nil))))
     (Info-title-1-face ((t (nil))))
     (Info-title-2-face ((t (nil))))
     (Info-title-3-face ((t (nil))))
     (Info-title-4-face ((t (:bold t :weight bold))))
     (OrangeRed ((t (nil))))
     (antlr-font-lock-keyword-face ((t (:bold t :foreground "black" :weight bold))))
     (antlr-font-lock-literal-face ((t (:bold t :foreground "brown4" :weight bold))))
     (antlr-font-lock-ruledef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-ruleref-face ((t (:foreground "blue4"))))
     (antlr-font-lock-tokendef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-tokenref-face ((t (:foreground "orange4"))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "blue4"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "Wheat" :foreground "DarkSlateGray"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (nil))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "LavenderBlush4"))))
     (button ((t (:underline t))))
     (bzr-added-face ((t (:bold t :foreground "lime green" :weight bold))))
     (bzr-conflict-face ((t (:bold t :foreground "red" :weight bold))))
     (bzr-deleted-face ((t (:bold t :foreground "dark orange" :weight bold))))
     (bzr-field-name-face ((t (:bold t :foreground "dark grey" :weight bold))))
     (bzr-modified-face ((t (:bold t :foreground "blue" :weight bold))))
     (bzr-renamed-face ((t (:bold t :foreground "purple" :weight bold))))
     (bzr-unknown-face ((t (:bold t :foreground "goldenrod" :weight bold))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "Firebrick"))))
     (change-log-acknowledgement-face ((t (:foreground "Firebrick"))))
     (change-log-conditionals ((t (:foreground "DarkGoldenrod"))))
     (change-log-conditionals-face ((t (:foreground "DarkGoldenrod"))))
     (change-log-date ((t (:foreground "green4"))))
     (change-log-date-face ((t (:foreground "green4"))))
     (change-log-email ((t (:foreground "DarkGoldenrod"))))
     (change-log-email-face ((t (:foreground "DarkGoldenrod"))))
     (change-log-file ((t (:foreground "Blue"))))
     (change-log-file-face ((t (:foreground "Blue"))))
     (change-log-function ((t (:foreground "DarkGoldenrod"))))
     (change-log-function-face ((t (:foreground "DarkGoldenrod"))))
     (change-log-list ((t (:foreground "Purple"))))
     (change-log-list-face ((t (:foreground "Purple"))))
     (change-log-name ((t (:foreground "CadetBlue"))))
     (change-log-name-face ((t (:foreground "CadetBlue"))))
     (clear-case-mode-string-face ((t (nil))))
     (clearcase-dired-checkedout-face ((t (nil))))
     (cmode-bracket-face ((t (nil))))
     (color-mode-face-@ ((t (nil))))
     (color-mode-face-a ((t (nil))))
     (color-mode-face-b ((t (nil))))
     (color-mode-face-c ((t (nil))))
     (color-mode-face-d ((t (nil))))
     (color-mode-face-e ((t (nil))))
     (color-mode-face-f ((t (nil))))
     (color-mode-face-g ((t (nil))))
     (color-mode-face-h ((t (nil))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "ForestGreen"))))
     (compilation-error ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-info ((t (:bold t :foreground "grey" :weight normal))))
     (compilation-line-number ((t (:foreground "darkgreen"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:stipple nil :background "white" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "fixed"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (nil))))
     (cparen-around-begin-face ((t (nil))))
     (cparen-around-conditional-face ((t (nil))))
     (cparen-around-define-face ((t (nil))))
     (cparen-around-lambda-face ((t (nil))))
     (cparen-around-letdo-face ((t (nil))))
     (cparen-around-quote-face ((t (nil))))
     (cparen-around-set!-face ((t (nil))))
     (cparen-around-syntax-rules-face ((t (nil))))
     (cparen-around-vector-face ((t (nil))))
     (cparen-binding-face ((t (nil))))
     (cparen-binding-list-face ((t (nil))))
     (cparen-conditional-clause-face ((t (nil))))
     (cparen-normal-paren-face ((t (nil))))
     (cperl-array-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :foreground "LavenderBlush4" :slant italic :weight bold))))
     (cperl-here-face ((t (nil))))
     (cperl-invalid-face ((t (nil))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cperl-pod-face ((t (nil))))
     (cperl-pod-head-face ((t (nil))))
     (cscope-file-face ((t (nil))))
     (cscope-function-face ((t (nil))))
     (cscope-line-face ((t (nil))))
     (cscope-line-number-face ((t (nil))))
     (cscope-mouse-face ((t (nil))))
     (cursor ((t (:background "black"))))
     (custom-button ((t (:background "lightgrey"))))
     (custom-button-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline nil))))
     (custom-button-unraised ((t (:underline nil))))
     (custom-changed ((t (:background "blue" :foreground "LavenderBlush4"))))
     (custom-changed-face ((t (:background "blue" :foreground "LavenderBlush4"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-face ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-comment-tag-face ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-documentation-face ((t (:foreground "grey40"))))
     (custom-face-tag ((t (:underline t))))
     (custom-face-tag-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (custom-group-tag ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-1 ((t (:foreground "MediumOrchid4" :underline t))))
     (custom-group-tag-face ((t (:bold t :foreground "blue" :weight bold :height 1.2))))
     (custom-group-tag-face-1 ((t (:bold t :foreground "red" :weight bold :height 1.2 :family "helv"))))
     (custom-invalid ((t (:background "red" :foreground "blue4"))))
     (custom-invalid-face ((t (:background "red" :foreground "blue4"))))
     (custom-link ((t (:foreground "blue1" :underline t))))
     (custom-modified ((t (:background "blue" :foreground "LavenderBlush4"))))
     (custom-modified-face ((t (:background "blue" :foreground "LavenderBlush4"))))
     (custom-rogue ((t (:background "black" :foreground "MediumOrchid4"))))
     (custom-rogue-face ((t (:background "black" :foreground "MediumOrchid4"))))
     (custom-saved ((t (:underline t))))
     (custom-saved-face ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-state-face ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "LavenderBlush4"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:foreground "light blue" :underline t))))
     (custom-variable-tag-face ((t (:bold t :foreground "blue" :weight bold :height 1.2 :family "helv"))))
     (custom-visibility ((t (:foreground "blue1" :underline t :height 0.8))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "MediumOrchid4"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (nil))))
     (date ((t (nil))))
     (diary-face ((t (:foreground "red"))))
     (diff-added ((t (nil))))
     (diff-added-face ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-context-face ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-file-header-face ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:foreground "grey50"))))
     (diff-function-face ((t (:foreground "grey50"))))
     (diff-header ((t (:background "grey85"))))
     (diff-header-face ((t (:background "grey85"))))
     (diff-hunk-header ((t (:background "grey85"))))
     (diff-hunk-header-face ((t (:background "grey85"))))
     (diff-index ((t (:bold t :background "grey70" :weight bold))))
     (diff-index-face ((t (:bold t :background "grey70" :weight bold))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :background "grey70" :weight bold))))
     (diff-nonexistent-face ((t (:bold t :background "grey70" :weight bold))))
     (diff-refine-change ((t (:background "grey90"))))
     (diff-removed ((t (nil))))
     (diff-removed-face ((t (nil))))
     (dired-directory ((t (nil))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (nil))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "gray20"))))
     (dired-flagged ((t (nil))))
     (dired-header ((t (nil))))
     (dired-ignored ((t (nil))))
     (dired-mark ((t (nil))))
     (dired-marked ((t (nil))))
     (dired-symlink ((t (nil))))
     (dired-warn-writable ((t (:bold t :foreground "MediumOrchid4" :weight bold))))
     (dired-warning ((t (nil))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (dvc-added ((t (:foreground "CadetBlue"))))
     (dvc-bookmark-name ((t (:foreground "blue4"))))
     (dvc-broken-link ((t (:bold t :weight bold :foreground "Red"))))
     (dvc-buffer ((t (:foreground "blue4"))))
     (dvc-comment ((t (:foreground "Firebrick"))))
     (dvc-conflict ((t (:bold t :weight bold :foreground "Red"))))
     (dvc-copy ((t (:foreground "Blue"))))
     (dvc-deleted ((t (:bold t :weight bold :foreground "Red"))))
     (dvc-duplicate ((t (:bold t :weight bold :foreground "Red"))))
     (dvc-excluded ((t (:foreground "orchid"))))
     (dvc-header ((t (:foreground "Blue"))))
     (dvc-highlight ((t (:background "gold"))))
     (dvc-id ((t (:foreground "Purple"))))
     (dvc-ignored ((t (:foreground "Firebrick"))))
     (dvc-keyword ((t (:foreground "Purple"))))
     (dvc-local-directory ((t (:foreground "blue4"))))
     (dvc-mark ((t (:bold t :foreground "green" :weight bold))))
     (dvc-marked ((t (:foreground "magenta"))))
     (dvc-messages ((t (:foreground "Blue"))))
     (dvc-meta-info ((t (:foreground "Firebrick"))))
     (dvc-modified ((t (:foreground "Blue"))))
     (dvc-move ((t (:foreground "CadetBlue"))))
     (dvc-nested-tree ((t (:foreground "ForestGreen"))))
     (dvc-repository-name ((t (:foreground "blue4"))))
     (dvc-revision-name ((t (:foreground "blue4"))))
     (dvc-separator ((t (:bold t :underline t :weight bold))))
     (dvc-source ((t (:foreground "green4"))))
     (dvc-to-add ((t (:foreground "Firebrick"))))
     (dvc-unknown ((t (:foreground "DarkGoldenrod"))))
     (dvc-unmerged ((t (:foreground "Purple"))))
     (dvc-unrecognized ((t (:bold t :weight bold :foreground "Red"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class-face ((t (:foreground "purple"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class-face ((t (:bold t :foreground "blue" :weight bold))))
     (ebrowse-tree-mark-face ((t (:foreground "red"))))
     (ecb-bucket-token-face ((t (nil))))
     (ecb-default-general-face ((t (nil))))
     (ecb-default-highlight-face ((t (nil))))
     (ecb-directories-general-face ((t (nil))))
     (ecb-directory-face ((t (nil))))
     (ecb-history-face ((t (nil))))
     (ecb-history-general-face ((t (nil))))
     (ecb-method-face ((t (nil))))
     (ecb-methods-general-face ((t (nil))))
     (ecb-source-face ((t (nil))))
     (ecb-source-in-directories-buffer-face ((t (nil))))
     (ecb-sources-face ((t (:foreground "brown3"))))
     (ecb-sources-general-face ((t (nil))))
     (ecb-token-header-face ((t (nil))))
     (ecb-type-token-class-face ((t (nil))))
     (ecb-type-token-enum-face ((t (nil))))
     (ecb-type-token-group-face ((t (nil))))
     (ecb-type-token-interface-face ((t (nil))))
     (ecb-type-token-struct-face ((t (nil))))
     (ecb-type-token-typedef-face ((t (nil))))
     (edb-inter-field-face ((t (nil))))
     (edb-normal-summary-face ((t (nil))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "blue4" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "indianred" :foreground "LavenderBlush4"))))
     (ediff-even-diff-face-A ((t (:background "light gray" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Gray" :foreground "LavenderBlush4"))))
     (ediff-even-diff-face-B ((t (:background "Gray" :foreground "LavenderBlush4"))))
     (ediff-even-diff-face-C ((t (:background "light gray" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Gray" :foreground "LavenderBlush4"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light gray" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light gray" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Gray" :foreground "LavenderBlush4"))))
     (eieio-custom-slot-tag-face ((t (nil))))
     (emacs-wiki-bad-link-face ((t (nil))))
     (emacs-wiki-link-face ((t (nil))))
     (erb-comment-delim-face ((t (:background "LemonChiffon" :foreground "Firebrick"))))
     (erb-comment-face ((t (:foreground "Firebrick"))))
     (erb-delim-face ((t (:foreground "burlywood3"))))
     (erb-exec-delim-face ((t (:foreground "burlywood3"))))
     (erb-exec-face ((t (:background "LemonChiffon"))))
     (erb-face ((t (:background "black"))))
     (erb-out-delim-face ((t (:foreground "burlywood3" :weight bold))))
     (erb-out-face ((t (:background "white"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (nil))))
     (erc-dangerous-host-face ((t (nil))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "LightSalmon"))))
     (erc-error-face ((t (:bold t :foreground "blue4" :weight bold))))
     (erc-fool-face ((t (nil))))
     (erc-highlight-face ((t (nil))))
     (erc-host-danger-face ((t (nil))))
     (erc-input-face ((t (:foreground "blue1"))))
     (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
     (erc-keyword-face ((t (nil))))
     (erc-nick-default-face ((t (nil))))
     (erc-nick-msg-face ((t (nil))))
     (erc-notice-face ((t (:foreground "MediumAquamarine"))))
     (erc-pal-face ((t (:foreground "DarkGreen"))))
     (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "purple3" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "grey40"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "purple3" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "blue4" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "purple3" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "purple3" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "purple3"))))
     (eshell-ls-product-face ((t (:foreground "purple3"))))
     (eshell-ls-readonly-face ((t (:foreground "purple3"))))
     (eshell-ls-special-face ((t (:bold t :foreground "purple3" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "LavenderBlush4" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "purple3"))))
     (eshell-ls-todo-face ((t (:foreground "purple3"))))
     (eshell-ls-unreadable-face ((t (:foreground "purple33"))))
     (eshell-prompt-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (extra-whitespace-face ((t (nil))))
     (face-1 ((t (nil))))
     (face-2 ((t (nil))))
     (face-3 ((t (nil))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (nil))))
     (fg:erc-color-face0 ((t (:foreground "LavenderBlush4"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "brown3"))))
     (fg:erc-color-face11 ((t (:foreground "DeepSkyBlue4"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray30"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "blue4"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "MediumOrchid4"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cadetblue"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "blue4"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flymake-errline ((t (:overline "red"))))
     (flymake-warnline ((t (:overline "orange"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "SaddleBrown"))))
     (font-latex-sedate-face ((t (:foreground "gray10"))))
     (font-latex-string-face ((t (:foreground "orange"))))
     (font-latex-warning-face ((t (:foreground "gold"))))
     (font-lock-builtin-face ((t (:foreground "Orchid"))))
     (font-lock-comment-delimiter-face ((t (:foreground "coral"))))
     (font-lock-comment-face ((t (:foreground "SaddleBrown"))))
     (font-lock-constant-face ((t (:foreground "DarkCyan"))))
     (font-lock-doc-face ((t (:bold t :weight bold))))
     (font-lock-doc-string-face ((t (:bold t :foreground "DarkSeaGreen" :weight bold))))
     (font-lock-emphasized-face ((t (nil))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:foreground "Blue" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (nil))))
     (font-lock-other-type-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "CadetBlue"))))
     (font-lock-reference-face ((t (:foreground "Orchid"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-special-comment-face ((t (nil))))
     (font-lock-special-keyword-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "green4"))))
     (font-lock-type-face ((t (:foreground "DarkOrange" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :foreground "DodgerBlue"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "DarkSlateBlue"))))
     (gdb-arrow-face ((t (nil))))
     (gnu-cite-face-3 ((t (nil))))
     (gnu-cite-face-4 ((t (nil))))
     (gnus-cite-attribution-face ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-cite-face-1 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-10 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-11 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-2 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-3 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-4 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-5 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-6 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-7 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-8 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-9 ((t (:foreground "DarkOrange"))))
     (gnus-cite-face-list ((t (nil))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "blue4"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "ForestGreen"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "indianred4" :slant italic))))
     (gnus-header-from-face ((t (:foreground "red3"))))
     (gnus-header-name-face ((t (:foreground "maroon"))))
     (gnus-header-newsgroups-face ((t (:italic t :foreground "MidnightBlue" :slant italic))))
     (gnus-header-subject-face ((t (:foreground "red4"))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (nil))))
     (gnus-server-closed-face ((t (nil))))
     (gnus-server-denied-face ((t (nil))))
     (gnus-server-offline-face ((t (nil))))
     (gnus-server-opened-face ((t (nil))))
     (gnus-signature-face ((t (:italic t :slant italic))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "blue4"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (nil))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "firebrick" :slant italic))))
     (gnus-summary-low-undownloaded-face ((t (nil))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "firebrick"))))
     (gnus-summary-normal-undownloaded-face ((t (nil))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "DarkSalmon" :foreground "LavenderBlush4"))))
     (gui-element ((t (:background "Gray"))))
     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "blue4"))))
     (highlight ((t (:background "darkseagreen2"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "SeaGreen"))))
     (highline-vertical-face ((t (nil))))
     (holiday-face ((t (:background "pink"))))
     (horizontal-divider ((t (nil))))
     (hproperty:but-face ((t (nil))))
     (hproperty:flash-face ((t (nil))))
     (hproperty:highlight-face ((t (nil))))
     (hproperty:item-face ((t (nil))))
     (html-helper-bold-face ((t (:foreground "DarkRed"))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (nil))))
     (html-helper-italic-face ((t (:foreground "DarkBlue"))))
     (html-helper-underline-face ((t (:foreground "Black" :underline t))))
     (html-tag-face ((t (:foreground "Blue"))))
     (hyper-apropos-documentation ((t (nil))))
     (hyper-apropos-heading ((t (nil))))
     (hyper-apropos-hyperlink ((t (nil))))
     (hyper-apropos-major-heading ((t (nil))))
     (hyper-apropos-section-heading ((t (nil))))
     (hyper-apropos-warning ((t (nil))))
     (ibuffer-deletion-face ((t (nil))))
     (ibuffer-marked-face ((t (nil))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-first-match-face ((t (nil))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Red"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-indicator-face ((t (nil))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-only-match-face ((t (nil))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-subdir-face ((t (nil))))
     (info-header-node ((t (nil))))
     (info-header-xref ((t (nil))))
     (info-menu-5 ((t (:underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold))))
     (info-node ((t (:italic t :bold t :slant italic :weight bold))))
     (info-xref ((t (:bold t :weight bold))))
     (isearch ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (ispell-face ((t (nil))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "DeepSkyBlue4"))))
     (jde-bug-breakpoint-marker ((t (:background "blue4" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "blue4" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "green4"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (kai-gnus-cite-face-1 ((t (nil))))
     (kai-gnus-cite-face-2 ((t (nil))))
     (kai-gnus-cite-face-3 ((t (nil))))
     (kai-gnus-group-mail-face ((t (nil))))
     (kai-gnus-group-nonempty-mail-face ((t (nil))))
     (kai-gnus-group-starred-face ((t (nil))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "LavenderBlush4"))))
     (log-view-file ((t (:bold t :background "grey70" :weight bold))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message ((t (:background "grey85"))))
     (log-view-message-face ((t (:background "grey85"))))
     (m4-face ((t (nil))))
     (magenta ((t (nil))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (nil))))
     (man-heading ((t (nil))))
     (man-italic ((t (nil))))
     (man-xref ((t (nil))))
     (match ((t (:background "blue4" :foreground "black"))))
     (menu ((t (:background "wheat" :foreground "gray30"))))
     (message-cited-text ((t (nil))))
     (message-cited-text-face ((t (:foreground "red"))))
     (message-header-cc-face ((t (:foreground "MidnightBlue"))))
     (message-header-contents ((t (nil))))
     (message-header-name-face ((t (:foreground "cornflower blue"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "blue4" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "steel blue"))))
     (message-header-subject-face ((t (:bold t :foreground "navy blue" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "MidnightBlue" :weight bold))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-headers ((t (nil))))
     (message-highlighted-header-contents ((t (nil))))
     (message-mml-face ((t (:foreground "ForestGreen"))))
     (message-separator-face ((t (:foreground "brown"))))
     (message-url ((t (nil))))
     (minibuffer-prompt ((t (:foreground "DeepSkyBlue4"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (nil))))
     (mode-line ((t (:background "SkyBlue" :foreground "black"))))
     (mode-line-buffer-id ((t (:background "SkyBlue" :foreground "black"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey20" :foreground "grey90" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (modeline-mousable ((t (:background "lightred" :foreground "black"))))
     (modeline-mousable-minor-mode ((t (:background "SkyBlue" :foreground "black"))))
     (mouse ((t (:background "LawnGreen"))))
     (mpg123-face-cur ((t (:background "#004080" :foreground "blue4"))))
     (mpg123-face-slider ((t (:background "blue4" :foreground "black"))))
     (my-summary-highlight-face ((t (:foreground "LavenderBlush4"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "DarkOrange"))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-colon-face ((t (:foreground "#257A25"))))
     (nxml-attribute-local-name ((t (:foreground "DarkGoldenrod"))))
     (nxml-attribute-local-name-face ((t (:foreground "#257A25"))))
     (nxml-attribute-prefix ((t (:foreground "Orchid"))))
     (nxml-attribute-prefix-face ((t (:foreground "#257A25"))))
     (nxml-attribute-value ((t (:foreground "green4"))))
     (nxml-attribute-value-delimiter ((t (:foreground "green4"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-attribute-value-face ((t (:foreground "#3A3A7B"))))
     (nxml-cdata-section-CDATA ((t (:foreground "Orchid"))))
     (nxml-cdata-section-CDATA-face ((t (:foreground "#257A25"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-char-ref-delimiter ((t (:foreground "CadetBlue"))))
     (nxml-char-ref-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-char-ref-number ((t (:foreground "CadetBlue"))))
     (nxml-char-ref-number-face ((t (:foreground "#9292C9"))))
     (nxml-comment-content ((t (:foreground "Firebrick"))))
     (nxml-comment-content-face ((t (:italic t :slant italic))))
     (nxml-comment-delimiter ((t (:foreground "Firebrick"))))
     (nxml-comment-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-delimited-data ((t (:bold t :weight bold))))
     (nxml-delimited-data-face ((t (:foreground "#3A3A7B"))))
     (nxml-delimiter ((t (nil))))
     (nxml-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-colon-face ((t (:foreground "#257A25"))))
     (nxml-element-local-name ((t (:foreground "Blue"))))
     (nxml-element-local-name-face ((t (:foreground "#257A25"))))
     (nxml-element-prefix ((t (:foreground "Orchid"))))
     (nxml-element-prefix-face ((t (:foreground "#257A25"))))
     (nxml-entity-ref-delimiter ((t (:foreground "CadetBlue"))))
     (nxml-entity-ref-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-entity-ref-name ((t (:foreground "CadetBlue"))))
     (nxml-entity-ref-name-face ((t (:foreground "#9292C9"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :family "misc-fixed"))))
     (nxml-glyph-face ((t (:background "light grey" :foreground "black" :slant normal :weight normal :family "misc-fixed"))))
     (nxml-hash ((t (:foreground "Orchid"))))
     (nxml-hash-face ((t (:foreground "#257A25"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-heading-face ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-name ((t (:foreground "Orchid"))))
     (nxml-name-face ((t (:foreground "#257A25"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-colon-face ((t (:foreground "#257A25"))))
     (nxml-namespace-attribute-prefix ((t (:foreground "DarkGoldenrod"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#257A25"))))
     (nxml-namespace-attribute-value ((t (:foreground "green4"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "green4"))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-namespace-attribute-value-face ((t (:foreground "#3A3A7B"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "Orchid"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#257A25"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "#FFFFE0" :foreground "black" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier" :box 1 :height 90))))
     (nxml-outline-active-indicator-face ((t (:stipple nil :background "white" :foreground "#000000" :inverse-video nil :box 1 :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "fixed"))))
     (nxml-outline-ellipsis ((t (:bold t :family "adobe-courier" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "#FFFFE0" :stipple nil :weight bold :height 90))))
     (nxml-outline-ellipsis-face ((t (:bold t :stipple nil :background "white" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 100 :width normal :family "fixed"))))
     (nxml-outline-indicator ((t (:family "adobe-courier" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "#FFFFE0" :stipple nil :height 90))))
     (nxml-outline-indicator-face ((t (:stipple nil :background "white" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "fixed"))))
     (nxml-processing-instruction-content ((t (:bold t :weight bold))))
     (nxml-processing-instruction-content-face ((t (:foreground "#3A3A7B"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-processing-instruction-target ((t (:foreground "Purple"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#257A25"))))
     (nxml-prolog-keyword ((t (:foreground "Purple"))))
     (nxml-prolog-keyword-face ((t (:foreground "#257A25"))))
     (nxml-prolog-literal-content ((t (:bold t :weight bold))))
     (nxml-prolog-literal-content-face ((t (:foreground "#3A3A7B"))))
     (nxml-prolog-literal-delimiter ((t (:bold t :weight bold))))
     (nxml-prolog-literal-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-ref ((t (:foreground "CadetBlue"))))
     (nxml-ref-face ((t (:foreground "#9292C9"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-delimiter-face ((t (:foreground "#9292C9"))))
     (nxml-tag-slash ((t (nil))))
     (nxml-tag-slash-face ((t (:foreground "#257A25"))))
     (nxml-text ((t (nil))))
     (nxml-text-face ((t (nil))))
     (overlay-empty-face ((t (nil))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:foreground "red"))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (paren-blink-off ((t (:foreground "gray"))))
     (paren-blink-on ((t (nil))))
     (paren-face ((t (nil))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "LavenderBlush4"))))
     (paren-face-no-match ((t (:background "blue4" :foreground "black"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
     (paren-mismatch-face ((t (:bold t :weight bold))))
     (paren-no-match-face ((t (:bold t :weight bold))))
     (pointer ((t (nil))))
     (primary-selection ((t (:background "lightgoldenrod2"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "blue4"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "gray"))))
     (right-margin ((t (nil))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (nil))))
     (ruler-mode-column-number-face ((t (nil))))
     (ruler-mode-current-column-face ((t (nil))))
     (ruler-mode-default-face ((t (nil))))
     (ruler-mode-fill-column-face ((t (nil))))
     (ruler-mode-margins-face ((t (nil))))
     (ruler-mode-tab-stop-face ((t (nil))))
     (sass-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (scroll-bar ((t (:background "grey75" :foreground "#000000"))))
     (searchm-buffer ((t (nil))))
     (searchm-button ((t (nil))))
     (searchm-field ((t (nil))))
     (searchm-field-label ((t (nil))))
     (searchm-highlight ((t (nil))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (:background "lightyellow"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (setnu-line-number-face ((t (nil))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "red"))))
     (sgml-end-tag-face ((t (:foreground "blue"))))
     (sgml-entity-face ((t (:foreground "magenta"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "green"))))
     (sgml-namespace ((t (:foreground "Orchid"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-shortref-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-start-tag-face ((t (:foreground "blue"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (shadow ((t (:foreground "grey50"))))
     (shell-input-face ((t (nil))))
     (shell-option-face ((t (:foreground "blue"))))
     (shell-output-2-face ((t (:foreground "darkseagreen"))))
     (shell-output-3-face ((t (:foreground "slategray"))))
     (shell-output-face ((t (:foreground "DarkGreen"))))
     (shell-prompt-face ((t (:foreground "red"))))
     (show-block-face1 ((t (nil))))
     (show-block-face2 ((t (nil))))
     (show-block-face3 ((t (nil))))
     (show-block-face4 ((t (nil))))
     (show-block-face5 ((t (nil))))
     (show-block-face6 ((t (nil))))
     (show-block-face7 ((t (nil))))
     (show-block-face8 ((t (nil))))
     (show-block-face9 ((t (nil))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "LavenderBlush4"))))
     (show-tabs-space-face ((t (:foreground "blue4"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (show-trailing-whitespace ((t (nil))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "blue"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (special-string-face ((t (nil))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "LavenderBlush4" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (tabbar-button-face ((t (nil))))
     (tabbar-default-face ((t (nil))))
     (tabbar-selected-face ((t (nil))))
     (tabbar-separator-face ((t (nil))))
     (tabbar-unselected-face ((t (nil))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (nil))))
     (term-blue-face ((t (nil))))
     (term-blue-inv-face ((t (nil))))
     (term-blue-ul-face ((t (nil))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "DeepSkyBlue4"))))
     (term-cyan-bold-face ((t (nil))))
     (term-cyan-face ((t (nil))))
     (term-cyan-inv-face ((t (nil))))
     (term-cyan-ul-face ((t (nil))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-default-bg ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-default-bg-inv ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-default-bold-face ((t (nil))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (:stipple nil :background "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-default-fg-inv ((t (:stipple nil :background "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-default-inv-face ((t (nil))))
     (term-default-ul-face ((t (nil))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (nil))))
     (term-green-face ((t (nil))))
     (term-green-inv-face ((t (nil))))
     (term-green-ul-face ((t (nil))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-invisible-inv ((t (:stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "adobe-courier"))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (nil))))
     (term-magenta-face ((t (nil))))
     (term-magenta-inv-face ((t (nil))))
     (term-magenta-ul-face ((t (nil))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (nil))))
     (term-red-face ((t (nil))))
     (term-red-inv-face ((t (nil))))
     (term-red-ul-face ((t (nil))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "LavenderBlush4"))))
     (term-white-bold-face ((t (nil))))
     (term-white-face ((t (nil))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (nil))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "blue4"))))
     (term-yellow-bold-face ((t (nil))))
     (term-yellow-face ((t (nil))))
     (term-yellow-inv-face ((t (nil))))
     (term-yellow-ul-face ((t (nil))))
     (term-yellowbg ((t (:background "blue4"))))
     (tex-math-face ((t (:foreground "green4"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:background "Red3" :foreground "LavenderBlush4"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "purple3"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "Gray"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-generic-/constant-face ((t (nil))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (nil))))
     (vhdl-font-lock-variable-face ((t (nil))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Gray50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Gray50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (nil))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "gray" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "purple3" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "purple3" :slant italic))))
     (vm-header-name-face ((t (:foreground "DeepSkyBlue4"))))
     (vm-header-subject-face ((t (:foreground "DeepSkyBlue4"))))
     (vm-header-to-face ((t (:italic t :foreground "DeepSkyBlue4" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (nil))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "LavenderBlush4"))))
     (vm-xface ((t (nil))))
     (vmpc-pre-sig-face ((t (:foreground "Aquamarine"))))
     (vmpc-sig-face ((t (:foreground "DarkOrange"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (nil))))
     (w3m-arrived-anchor-face ((t (nil))))
     (w3m-header-line-location-content-face ((t (nil))))
     (w3m-header-line-location-title-face ((t (nil))))
     (white ((t (nil))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "blue1"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (nil))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (nil))))
     (x-symbol-info-face ((t (nil))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (nil))))
     (xrdb-option-name-face ((t (nil))))
     (xrdb-option-value-face ((t (nil))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (nil))))
     (xsl-fo-main-face ((t (nil))))
     (xsl-other-element-face ((t (nil))))
     (xsl-xslt-alternate-face ((t (nil))))
     (xsl-xslt-main-face ((t (nil))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "blue4"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey40" :underline t))))
     (yaml-tab-face ((t (:bold t :background "red" :foreground "red" :weight bold))))
     (yellow ((t (:foreground "blue4"))))
     (zmacs-region ((t (:background "lightgoldenrod2")))))))
